# Generated by Django 4.0.4 on 2022-05-16 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rate', models.FloatField(default=None)),
                ('description', models.CharField(max_length=200)),
                ('is_damaged', models.BooleanField(default=False)),
                ('damage', models.CharField(default=None, max_length=500)),
                ('is_available', models.BooleanField(default=True)),
                ('rent_end_date', models.DateTimeField(default=None)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='category.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='user.user')),
            ],
        ),
    ]
