# Generated by Django 4.0.4 on 2022-05-19 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rented_date', models.DateTimeField(default=None, null=True)),
                ('renting_days', models.IntegerField(default=None, null=True)),
                ('status', models.CharField(choices=[('0', 'NO RESPONSE'), ('1', 'ACCEPTED'), ('2', 'REJECTED')], default='0', max_length=1)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_lend', to='user.user')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rent', to='product.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_rent', to='user.user')),
            ],
        ),
    ]
